defaults: &defaults
 adapter:  <%= Appconfig::Database::DB_ADAPTER %>
 encoding: <%= Appconfig::Database::DB_ENCODING %>
 username: <%= Appconfig::Database::DB_USER %>
 host: <%= Appconfig::Database::DB_HOST %>

development:
  <<: *defaults
  database: <%= Appconfig::Database::DEVELOPMENT_DB %>
  password: ''

test: &test
  <<: *defaults
  database: <%= Appconfig::Database::TEST_DB %>
  password: ''

production:
  <<: *defaults
  database: <%= Appconfig::Database::PRODUCTION_DB %>
  password: <%= Appconfig::Database::PRODUCTION_DB_PASSWORD %>